---
title: "RWorksheet4_Frias"
output: pdf_document
date: "2022-12-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r setup1, include=TRUE}

#1.The table below shows the data about shoe size and height.
#Create a data frame.

sho_size <- c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,
            10.5,8.5,12.0,10.5)
height <- c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,
          64.0,74.5,67.0,71.0,71.0)
gen1 <- c("F","F","F","F","M","F","F","F","M","F","M",
         "F","M","M")
SHO_size <- c(13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,
            8.5,10.5,11.0,9.0,13.0)
HEIGHT <- c(77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,
          69.0,72.0,70.0,69.0,70.0)
Gen2 <- c("M","M","F","F","M","F","F","M","M","F",
         "M","M","M","M")

all <- data.frame(sho_size,height, gen1, SHO_size, 
                   HEIGHT, Gen2)
all
```

```{r setup2, include= TRUE}
#a. Describe the data. 
#The data shows the different shoe size among male and 
#female in different heights.

#b. Find the mean of shoe size and height of the respondents. Copy the codes and results.

Me <- mean(sho_size)
Me
```

```{r setup3, include=TRUE}
Mi <- mean(SHO_size)
Mi
```

```{r setup4, include=TRUE}
Ttl <- c(Me, Mi)
Ttl
```

```{r setup5, include=TRUE} 
# Total shoe size mean.
szmean <- mean(Ttl)
szmean
```

```{r setup6, include=TRUE} 
Mo <- mean(height)
Mo
```

```{r setup7, include=TRUE}
Mu <- mean(HEIGHT)
Mu
```

```{r setup8, include=TRUE}
aTtl <- c(Mo, Mu)
aTtl
```

```{r setup9, include=TRUE}
# Total height mean.
hght_mean <- mean(aTtl)
hght_mean
```

```{r, include=TRUE}
#c. Is there a relationship between shoe size and height? Why?
#Yes, there is a relationship between shoe size and height, 
#the shoe sizes is big when the respondents is also tall.
#If the height of the respondents is below 70.0 their shoe 
#size will be small.

#Factors
```

```{r setup10, include= TRUE}
#2.Construct character vector months to a factor with factor() 
#and assign the result to factor_months_vector. Print out 
#factor_months_vector and assert that R prints out the 
#factor levels below the actual values.Consider data 
#consisting of the names of months:

Months_vctr <- c("March","April","January","November",
                   "January","September","October","September",
                   "November","August","January","November",
                   "November", "February","May","August",
                   "July","December","August",
                   "August","September","November",
                   "February","April")

factor_months_vector <- factor(x = Months_vctr)
factor_months_vector
```

```{r setup11, include=TRUE}
# 3. Then check the summary() of the months_vector and 
#factor_months_vector. Interpret the results of both vectors.
#Are they both equally useful in this case?

smy <- summary(Months_vctr)
smy

smy1 <- summary(factor_months_vector)
smy1

##Both of the vector summary are useful because at the 
##summary of months_vector tells us about the length, class, 
##and mode. In summary of factor_months_vector it tells 
##us how many repeating elements there are.
```

```{r setup12, include=TRUE}
# 4. Create a vector and factor for the table below.

Drctn <- c("East", "West", "North") 
Frqncy <- c(1, 4, 3)
Mine <- factor(Drctn)
Yours<- factor(Frqncy)
print(Mine)
print(Yours)
```

```{r setup13, include=TRUE}
#5. Enter the data below in Excel with 
#file name = import_march.csv

#a.Import the excel file into the Environment Pane using
#read.table() function. Write the code.
L <- read.table("/cloud/project/import_march.csv", header= TRUE, sep= "," )
L
```

```{r, include=TRUE}
#b. View the dataset. Write the code and its result.
E <- read.csv("/cloud/project/import_march.csv")
E

```
